# Generated by Django 5.0.3 on 2026-06-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IncrementLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_type",
                    models.CharField(
                        choices=[("office", "Office Staff"), ("site", "Site Employee")],
                        default="office",
                        max_length=10,
                    ),
                ),
                ("employee_name", models.CharField(max_length=200)),
                ("employee_id", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=200)),
                ("promotion_designation", models.CharField(blank=True, max_length=200)),
                ("letter_date", models.DateField()),
                ("effective_date", models.DateField()),
                ("ref_no", models.CharField(max_length=100)),
                (
                    "basic_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "hra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "special_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "telephone_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pf_employer",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gratuity_provision",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "food_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "meal_card_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "professional_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "insurance_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pf_employee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "retention_bonus_annual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "variable_pay_fy2026_27",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "variable_pay_fy2025_26",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_ctc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "gross_monthly",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
