# Generated by Django 5.0.3 on 2026-06-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incrementletter",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="incrementletter",
            name="gross_monthly",
        ),
        migrations.RemoveField(
            model_name="incrementletter",
            name="total_ctc",
        ),
        migrations.AlterField(
            model_name="incrementletter",
            name="ref_no",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
