# Generated by Django 5.0.3 on 2026-07-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_incrementletter_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incrementletter",
            name="gratuity_provision",
        ),
        migrations.AddField(
            model_name="incrementletter",
            name="gross_a_revised_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Gross A / Revised Salary",
                max_digits=12,
            ),
        ),
    ]
