# Generated by Django 5.0.3 on 2026-07-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_incrementletter_gratuity_provision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incrementletter",
            name="food_allowance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Food Allowance (Monthly)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="incrementletter",
            name="insurance_premium",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Insurance Premium (Monthly)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="incrementletter",
            name="meal_card_deduction",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Meal Card Deduction (Monthly)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="incrementletter",
            name="pf_employee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Provident Fund Employee (Monthly)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="incrementletter",
            name="pf_employer",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Provident Fund Employer (Monthly)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="incrementletter",
            name="professional_tax",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Professional Tax (Monthly)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="incrementletter",
            name="ref_no",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="incrementletter",
            name="retention_bonus_annual",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Retention Bonus (Annual)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="incrementletter",
            name="telephone_allowance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Telephone Allowance (Monthly)",
                max_digits=12,
            ),
        ),
    ]
